name: Auto Format

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  format:
    name: Format files with Prettier
    runs-on: ubuntu-latest

    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ github.token }}

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install Prettier
        run: |
          npm install --no-save prettier

      - name: Run Prettier
        run: |
          npx prettier \
            "*.md" \
            "*.json" \
            "themes/*.yaml" \
            "*.yml" \
            ".github/release.yml" \
            "release-notes/**/*.md" \
            --write

      - name: Commit formatting changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add .
            git commit -m "Apply automated formatting"
            git push
          else
            echo "No formatting changes needed."
          fi
