name: Markdown Link Check

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 12 * * 1"

permissions:
  contents: read

jobs:
  markdown-link-check:
    name: Check markdown links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"